version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: notebook-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: notebook_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - notebook-network

  notebook-app:
    image: notebook-app:v1.0.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notebook-app
    restart: always
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/notebook_db?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - notebook-network

networks:
  notebook-network:
    driver: bridge

volumes:
  mysql-data: